serviceFront:
  web:
    build: frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/tasktracker
      - /tasktracker/node_modules
serviceBack:
  web:
    build: backend
    ports:
      - 4200:4200
    volumes:
      - ./backend:/tasktracker
      - /tasktracker/node_modules
