services:
  front:
      build: frontend
      ports:
        - 4200:4200
      volumes:
        - ./frontend:/tasktracker
        - /tasktracker/node_modules

  backend:
      build: backend
      ports:
        - 5000:5000
      volumes:
        - ./backend:/tasktracker

